config/routes.rb
Rails.application.routes.draw do

  root 'listings#index'

  resources :passwords, controller: "clearance/passwords", only: [:create, :new]

  resources :listings, only: [:index] do
    resources :reservations, only: [:create, :show]
  end

  resources :users, controller: "users", only: [:edit, :update, :create, :show] do
    resource :password,
      controller: "clearance/passwords",
      only: [:create, :edit, :update]
    resources :listings
    resources :reservations, only: [:index] do
      member do
        get 'payment'
        post 'checkout'
      end
    end
  end

  get '/admin' => "admin#show", as: "admin"
  get '/admin/verify' => "admin#verify", as: "admin_verify"
  post '/admin/verify/:id' => "admin#confirm", as: "admin_confirm"
  
  post "/session" => "sessions#create"
  get "/auth/:provider/callback" => "sessions#create_from_omniauth"  
  get "/sign_in" => "clearance/sessions#new", as: "sign_in"
  delete "/sign_out" => "clearance/sessions#destroy", as: "sign_out"
  get "/sign_up" => "users#new", as: "sign_up"

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/listing.rb
class Listing < ApplicationRecord
	belongs_to :user
  has_many :reservations
  mount_uploaders :pictures, PropertyPictureUploader
end

app/controllers/listings_controller.rb
class ListingsController < ApplicationController

  # GET    /listings(.:format)  
  # GET    /users/:user_id/listings(.:format)
	def index
    if params[:user_id]
      user = User.find(params[:user_id])
      @listings = user.listings
    else
  		@listings = Listing.where(verify: true)
    end
	end

  # GET    /users/:user_id/listings/:id(.:format) 
	def show
    user = User.find(params[:user_id])
		@listing = user.listings.find(params[:id])
    @reservation = @listing.reservations.new
    reservations = Reservation.where(listing_id: params[:id]).map{|x| {from: x.start_date, to: x.end_date.prev_day}}
    gon.reservations = reservations
	end

  # GET    /users/:user_id/listings/new(.:format)   
	def new
    if signed_in?
		  @listing = current_user.listings.new
    else
      flash[:notice] = "Please sign in before create listing."
      redirect_to sign_in_path
    end
	end

  # POST   /users/:user_id/listings(.:format) 
	def create
		@listing = current_user.listings.new(listing_from_params)
		if @listing.save
			redirect_to user_listing_path(current_user, @listing)
		else
			render "new"
		end
	end

  # GET    /users/:user_id/listings/:id/edit(.:format)
	def edit
    if signed_in? && (current_user.id == params[:user_id].to_i)
  		@listing = current_user.listings.find(params[:id])
    else
      flash[:notice] = "Please sign in before edit listing."
      redirect_to sign_in_path
    end
	end

  # PATCH  /users/:user_id/listings/:id(.:format) 
	def update
		@listing = current_user.listings.find(params[:id])
		if current_user.id = @listing.user_id
			@listing.update_attributes!(listing_from_params)
			redirect_to user_listing_path(current_user, @listing)
		else
			redirect_to root
		end
	end 

  # DELETE /users/:user_id/listings/:id(.:format)  
	def destroy
    @listing = Listing.find(params[:id])
		if (current_user.id = @listing.user_id) || current_user.admin?
			@listing.destroy
      if current_user.admin?
        redirect_to admin_verify_path		 
      else
        redirect_to user_listing_path(current_user, @listing)
      end
		else
			redirect_to root
		end
	end

	private

	def listing_from_params
		params.require(:listing).permit(:name, :property_type, :room_number, :bed_number, :guest_number, :country, :state, :city, :zipcode, :address, :price, :description, :user_id, {pictures: []})
	end

end

app/helpers/listings_helper.rb
module ListingsHelper
end

app/views/listings/_form.html.erb
	<div class="form-group row">
    <%= form.label :name, class: "col-sm-2 col-form-label" %>
    <div class="col-sm-4">
      <%= form.text_field :name, class: "form-control" %>
    </div>
  </div>

  <div class="form-group row">
    <%= form.label :property_type, class: "col-sm-2 col-form-label" %>
    <div class="col-sm-3">
      <%= form.select(:property_type, ["House", "Entire Floor", "Condominium", "Villa", "Townhouse", "Castle", "Treehouse", "Igloo", "Yurt", "Cave", "Chalet", "Hut", "Tent", "Other"], {}, {class: "form-control"}) %>
    </div>
  </div>

  <div class="form-group row">
    <%= form.label :room_number, class: "col-sm-2 col-form-label" %>
    <div class="col-sm-3">
      <%= form.select(:room_number, [0,1,2,3,4,5], {}, {class: "form-control"}) %>
    </div>
  </div>

  
  <div class="form-group row">
    <%= form.label :bed_number, class: "col-sm-2 col-form-label" %>
    <div class="col-sm-3">
      <%= form.select(:bed_number, [1,2,3,4,5,6], {}, {class: "form-control"}) %>
    </div>
  </div>

  <div class="form-group row">
    <%= form.label :guest_number, class: "col-sm-2 col-form-label" %>
    <div class="col-sm-3">
      <%= form.select(:guest_number, [1,2,3,4,5,6,7,8,9,10], {}, {class: "form-control"}) %>
    </div>
  </div>

  <div class="form-group row">
    <%= form.label :address, class: "col-sm-2 col-form-label" %>
    <div class="col-sm-4">
      <%= form.text_field :address, class: "form-control" %>
    </div>
  </div>

  <div class="form-group row">
    <%= form.label :country, class: "col-sm-2 col-form-label" %>
    <div class="col-sm-4">
      <%= form.text_field :country, class: "form-control" %>
    </div>
  </div>

  <div class="form-group row">
    <%= form.label :state, class: "col-sm-2 col-form-label" %>
    <div class="col-sm-4">
      <%= form.text_field :state, class: "form-control" %>
    </div>
  </div>  
  
  <div class="form-group row">
    <%= form.label :city, class: "col-sm-2 col-form-label" %>
    <div class="col-sm-4">
      <%= form.text_field :city, class: "form-control" %>
    </div>
  </div>

  <div class="form-group row">
    <%= form.label :zipcode, class: "col-sm-2 col-form-label" %>
    <div class="col-sm-4">
      <%= form.text_field :zipcode, class: "form-control" %>
    </div>
  </div>

  <div class="form-group row">
    <%= form.label :price, class: "col-sm-2 col-form-label" %>
    <div class="col-sm-4">
      <%= form.text_field :price, class: "form-control" %>
    </div>
  </div>

  <div class="form-group row">
    <%= form.label :description, class: "col-sm-2 col-form-label" %>
    <div class="col-sm-4">
      <%= form.text_field :description, class: "form-control" %>
    </div>
  </div>

  <div class="form-group">
    <%= form.label :pictures %>
    <%= form.file_field :pictures, multiple: true, class: "form-control-file" %>
  </div>

app/views/listings/edit.html.erb
<h2>Update</h2>

<%= form_for [current_user, @listing], html: {multipart: true} do |form| %>
  <%= render partial: '/listings/form', object: form %>

  <div class="submit-field">
    <%= form.submit class: "btn btn-primary" %>
  </div>

<% end %>

app/views/listings/index.html.erb
<% if @listings %>
  <% for listing in @listings %>
    <p><%= link_to listing.name, user_listing_path(listing.user, listing) %></p>
    <%= "Verify" if listing.verify? %>
  <% end %>
<% end %>

app/views/listings/new.html.erb
<h2>New Listing</h2>
<%= form_for [current_user, @listing], html: {multipart: true} do |form| %>

  <%= render partial: '/listings/form', object: form %>

  <div class="submit-field">
    <%= form.submit class: "btn btn-primary" %>
  </div>

<% end %>

app/views/listings/show.html.erb
<%= form_for [@listing, @reservation] do |f| %>

  <input id="reservation-date" class="flatpickr flatpickr-input active" name="reservation[date]" type="text" placeholder="<%= Date.today %>" data-id="datetime" readonly="readonly">
  <div class="submit-field">
    <%= f.submit class: "btn btn-primary" %>
  </div>

<% end %>

<p><%= @listing.name %></p>
<% if @listing.pictures? %>
  <% for item in @listing.pictures %>
    <%= image_tag(item) %>
  <% end %>
<% end %>
<%= "Verify" if @listing.verify? %>
<% if current_user.id == @listing.user_id %>
  <%= link_to 'Update', edit_user_listing_path(current_user, @listing), {class: "btn btn-primary"} %>
  <%= link_to 'Destroy', user_listing_path(current_user, @listing),
            data: {:confirm => 'Are you sure?'}, :method => :delete %>
<% end %>