config/routes.rb
Rails.application.routes.draw do

  root 'listings#index'

  resources :passwords, controller: "clearance/passwords", only: [:create, :new]

  resources :listings, only: [:index] do
    resources :reservations, only: [:create, :show]
  end

  resources :users, controller: "users", only: [:edit, :update, :create, :show] do
    resource :password,
      controller: "clearance/passwords",
      only: [:create, :edit, :update]
    resources :listings
    resources :reservations, only: [:index] do
      member do
        get 'payment'
        post 'checkout'
      end
    end
  end

  get '/admin' => "admin#show", as: "admin"
  get '/admin/verify' => "admin#verify", as: "admin_verify"
  post '/admin/verify/:id' => "admin#confirm", as: "admin_confirm"
  
  post "/session" => "sessions#create"
  get "/auth/:provider/callback" => "sessions#create_from_omniauth"  
  get "/sign_in" => "clearance/sessions#new", as: "sign_in"
  delete "/sign_out" => "clearance/sessions#destroy", as: "sign_out"
  get "/sign_up" => "users#new", as: "sign_up"

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/reservation.rb
class Reservation < ApplicationRecord
  belongs_to :user
  belongs_to :listing

  validates :start_date, presence: true
  validates :end_date, presence: true
  validate :check_overlapping_dates, on: :create

  before_save :total_amount_calculate

  def check_overlapping_dates
    listing.reservations.each do |old_booking|
      if (old_booking.id)
        if overlap?(self, old_booking)
          return errors.add(:check_overlapping_dates, "The booking dates conflict with existing booking")
        end
      end
    end
  end

  private

  def overlap?(x, y)
    (x.start_date - y.end_date) * (y.start_date - x.end_date) > 0
  end

  def total_amount_calculate
    self.total_amount = (self.end_date - self.start_date) * self.listing.price
  end

end

app/controllers/reservations_controller.rb
class ReservationsController < ApplicationController
  def create
    date = params[:reservation][:date].partition(' to ')
    params[:reservation][:start_date] = date[0]
    params[:reservation][:end_date] = date[2]
    listing = Listing.find(params[:listing_id])
    reservation = listing.reservations.new(reservation_params)
    reservation.user_id = current_user.id
    if reservation.save
      redirect_to  payment_user_reservation_path(reservation.user, reservation)
    else
      flash[:notice] = reservation.errors.messages
      redirect_to  user_listing_path(listing.user, listing)
    end
  end

  def index
    user = User.find(params[:user_id])
    @reservations = user.reservations
  end

  def payment
    @reservation = Reservation.find(params[:id])
    @client_token = Braintree::ClientToken.generate
    gon.clientToken = @client_token
  end

  def checkout
    reservation = Reservation.find(params[:id])
    nonce_from_the_client = params[:checkout_form][:payment_method_nonce]
    result = Braintree::Transaction.sale(
     :amount => reservation.total_amount, #this is currently hardcoded
     :payment_method_nonce => nonce_from_the_client,
     :options => {
        :submit_for_settlement => true
      }
     )
    if result.success?
      reservation.update(paid_status: true)
      ReservationJob.perform_later(current_user, reservation.listing.user, params[:id])
      redirect_to :root, :flash => { :success => "Transaction successful!" }
    else
      redirect_to :root, :flash => { :error => "Transaction failed. Please try again." }
    end 
  end

  private

  def reservation_params
    params.require(:reservation).permit(:start_date, :end_date)
  end
end

app/helpers/reservations_helper.rb
module ReservationsHelper
end

app/views/reservations/index.html.erb
<% if !@reservations %>
  <% for reservation in @reservations %>
    <p>reservation.id</p>
  <% end %>
<% end %>

app/views/reservations/payment.html.erb
<div class="demo-frame">  

  <%= form_for :checkout_form, url: checkout_user_reservation_path, html: { id: "cardForm"} do |form| %>

    <%= form.label :card_number, "Credit Card Number", html: {class: "hosted-fields--label"} %>
    <div id="card-number" class="hosted-field"></div>

    <%= form.label :expiration_date, "Expiration Date", html: {class: "hosted-fields--label"} %>      
    <div id="expiration-date" class="hosted-field"></div>

    <%= form.label :cvv, "CVV", html: {class: "hosted-fields--label"} %>
    <div id="cvv" class="hosted-field"></div>

    <%= form.hidden_field "payment_method_nonce" %>

    <div class="button-container">
      <%= form.submit "Purchase", disabled: true, class: "button button--small button--green", id: "submit-payment-btn" %>
    </div>

  <% end %>

</div>