config/routes.rb
Rails.application.routes.draw do

  root 'listings#index'

  resources :passwords, controller: "clearance/passwords", only: [:create, :new]

  resources :listings, only: [:index] do
    resources :reservations, only: [:create, :show]
  end

  resources :users, controller: "users", only: [:edit, :update, :create, :show] do
    resource :password,
      controller: "clearance/passwords",
      only: [:create, :edit, :update]
    resources :listings
    resources :reservations, only: [:index] do
      member do
        get 'payment'
        post 'checkout'
      end
    end
  end

  get '/admin' => "admin#show", as: "admin"
  get '/admin/verify' => "admin#verify", as: "admin_verify"
  post '/admin/verify/:id' => "admin#confirm", as: "admin_confirm"
  
  post "/session" => "sessions#create"
  get "/auth/:provider/callback" => "sessions#create_from_omniauth"  
  get "/sign_in" => "clearance/sessions#new", as: "sign_in"
  delete "/sign_out" => "clearance/sessions#destroy", as: "sign_out"
  get "/sign_up" => "users#new", as: "sign_up"

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>PairBnb</title>
    <%= csrf_meta_tags %>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/css/bootstrap.min.css" integrity="sha384-/Y6pD6FV/Vv2HJnA6t+vslU6fwYXjCFtcEpHbNJ0lyAFsXTsjBbfaDjzALeQsN6M" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.11.0/umd/popper.min.js" integrity="sha384-b/U6ypiBEHpOf/4+1nzFpr53nxSS+GLCkfwBdFNTxtclqqenISfwAzpKaMNFNmj4" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/js/bootstrap.min.js" integrity="sha384-h0AbiXch4ZDo7tp9hKZ4TsHbi047NrKGLO3SEJAg45jXxnGIfYzk4Si90RDIqNm1" crossorigin="anonymous"></script>
    <script src="https://js.braintreegateway.com/web/3.6.3/js/client.min.js"></script>
    <script src="https://js.braintreegateway.com/web/3.6.3/js/hosted-fields.min.js"></script>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= Gon::Base.render_data %>
</head>
<body>
  <nav class="navbar fixed-top navba-light">
    <div class="nav">
      <%= link_to image_tag("airbnb.png", size: "30x30"), root_path %>
    </div>
    <ul class="nav justify-content-end">
      <% if signed_in? %>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false"><%= image_tag(current_user.picture_url, class: "picture-thumbnail") %></a>
          <div class="dropdown-menu dropdown-right">
            <%= link_to "My Profile", user_path(current_user), class:"dropdown-item" %>
            <%= link_to "My Listings", user_listings_path(current_user), class:"dropdown-item" %>
            <%= link_to "My Reservations", user_reservations_path(current_user), class:"dropdown-item" %>
          </div>
        </li>
      <% end %>
    </ul>
  </nav>

  <div id="header">
    <% if signed_in? -%>
      <%= button_to t(".sign_out"), sign_out_path, method: :delete %>
    <% else -%>
      <%= link_to t(".sign_in"), sign_in_path %>
    <% end -%>
  </div>

  <div id="flash">
    <% flash.each do |key, value| -%>
      <div id="flash_<%= key %>"><%=h value %></div>
    <% end %>
  </div>

  <%= yield %>
</body>
</html>